# Generated by Django 4.0.2 on 2022-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
