# Generated by Django 4.0.2 on 2022-09-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docsapp', '0002_alter_users_mobile_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
