# Generated by Django 4.0.2 on 2022-09-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docsapp', '0004_alter_user_email_alter_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=452),
            preserve_default=False,
        ),
    ]
